#pragma once

#define CRED_LENGTH 128
#define LOGIN_SP_NO_PARAMS 4
#define SIGNUP_SP_NO_PARAMS 8
#define CUSTOMER_CODE_MAX_LENGTH 16
#define NAME_LENGTH 32
#define ADDRESS_LENGTH 64
#define CONTACT_LENGTH 256
#define INT_STR_LENGTH 10


#define REALSIZE(x) (x) + 1